services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
